name: Run Spectral

on: [push, pull_request]

jobs:
  lint:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: stoplightio/spectral-action@v0.7.0
        with:
          file_glob: "./Lob-API-public.yml"
